name: Build and Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build storybook
      run: npm run build-storybook

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v3
      with:
        name: production-files
        path: ./storybook-static
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: production-files
        path: production-files

    - name: Display structure of downloaded files
      run: ls -R
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload to Azure blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az account set --subscription ${{ secrets.SUBSCRIPTION }}
            az storage blob upload-batch --account-name ${{ secrets.ACCOUNT_NAME }} -d '$web' -s './production-files' --subscription ${{ secrets.SUBSCRIPTION }}

    - name: Azure logout
      run: |
            az logout

